from generate_all_faction_lists import slot, u

# ---------------------------------------------------------------------------
# Genestealer Cults unit datasheets (Apoc_Datasheet_Genestealers_web.pdf)
# ---------------------------------------------------------------------------

GENESTEALER_CULTS = {
    "Patriarch": u(
        "Patriarch",
        {"M": '9"', "WS": "2+", "BS": "5+", "A": "1", "W": "1", "Ld": "8", "Sv": "7+", "N": "1", "Pt": "7"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Psyker", "Character", "Genestealer", "Patriarch"],
        [{"name": "Monstrous Rending Claws", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "4+", "armorPen": "7+"}],
        'Brood Telepathy: Add 1 to hit rolls for attacks made with melee weapons by <Cult> Genestealer units whilst they are within 6" of any friendly <Cult> units with this ability.\n'
        'Living Idol: Morale tests taken for friendly <Cult> units are automatically passed whilst they are within 6" of this unit.',
        options=["A Patriarch is a unit that contains 1 model. It is equipped with: Monstrous Rending Claws."],
    ),
    "Magus": u(
        "Magus",
        {"M": '6"', "WS": "3+", "BS": "3+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "1", "Pt": "4"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Psyker", "Character", "Magus"],
        [{"name": "Magus Force Weapon", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "10+", "armorPen": "10+"}],
        'Spiritual Leader: Friendly <Cult> units can use this unit\'s Leadership characteristic instead of their own whilst they are within 6" of this unit.\n'
        "Master Psyker: Once per battle, at the end of the Orders phase, you can look through your Command Asset deck and draw either one Genestealer Cults Command Asset of your choice that is a psychic power, or the Deny the Witch or Adamantium Will card. Add the drawn card to your hand, then shuffle the Command Asset deck and place it face down.",
        options=["A Magus is a unit that contains 1 model. It is equipped with: Magus Force Weapon."],
    ),
    "Primus": u(
        "Primus",
        {"M": '6"', "WS": "2+", "BS": "3+", "A": "1", "W": "1", "Ld": "7", "Sv": "10+", "N": "1", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Primus"],
        [{"name": "Elite Cult Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "8+", "armorPen": "8+"}],
        'Cult Demagogue: Add 1 to hit rolls for attacks made with melee weapons by <Cult> units whilst they are within 6" of any friendly <Cult> units with this ability.',
        options=["A Primus is a unit that contains 1 model. It is equipped with: Elite Cult Weapons."],
    ),
    "Abominant": u(
        "Abominant",
        {"M": '6"', "WS": "3+", "BS": "6+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "1", "Pt": "4"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Aberrant", "Abominant"],
        [{"name": "Power Sledgehammer", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "6+", "armorPen": "7+"}],
        "Ignore Damage (6+)\n"
        'The Chosen One: When an unmodified hit roll of 6+ is rolled for an attack made with a melee weapon by a <Cult> Aberrant unit whilst it is within 6" of any friendly <Cult> units with this ability, that attack scores 2 hits instead of 1 – make a separate wound roll for each hit.',
        options=["An Abominant is a unit that contains 1 model. It is equipped with: Power Sledgehammer."],
    ),
    "Acolyte Hybrids": u(
        "Acolyte Hybrids",
        {"M": '6"', "WS": "3+", "BS": "4+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "5", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Acolyte Hybrids"],
        [
            {"name": "Demolition Charge", "type": "Heavy", "range": '6"', "attacks": "1", "skill": "6+", "armorPen": "4+", "abilities": "One Use Only"},
            {"name": "Acolyte Weapons", "type": "Small Arms", "range": '12"', "attacks": "User", "skill": "7+", "armorPen": "9+"},
            {"name": "Heavy Rock Drill", "type": "Melee", "range": "Melee", "attacks": "1", "skill": "8+", "armorPen": "5+"},
            {"name": "Heavy Rock Saw", "type": "Melee", "range": "Melee", "attacks": "1", "skill": "5+", "armorPen": "8+"},
            {"name": "Rending Claws", "type": "Melee", "range": "Melee", "attacks": "x2", "skill": "6+", "armorPen": "8+"},
        ],
        profiles=[
            {"M": '6"', "WS": "3+", "BS": "4+", "A": "2", "W": "2", "Ld": "6", "Sv": "10+", "N": "10", "Pt": "6"},
            {"M": '6"', "WS": "3+", "BS": "4+", "A": "3", "W": "3", "Ld": "6", "Sv": "10+", "N": "15", "Pt": "9"},
            {"M": '6"', "WS": "3+", "BS": "4+", "A": "4", "W": "4", "Ld": "6", "Sv": "10+", "N": "20", "Pt": "12"},
        ],
        options=[
            "Acolyte Hybrids are a unit that contains 5 models. It can contain 10 models (Power Rating 6), 15 models (Power Rating 9) or 20 models (Power Rating 12). It is equipped with: Acolyte Weapons; Rending Claws.",
            "For every 5 models this unit contains, it can also be equipped with up to two of the following in any combination (Power Rating +1 per weapon): 1 Demolition Charge; 1 Heavy Rock Drill; 1 Heavy Rock Saw.",
        ],
    ),
    "Neophyte Hybrids": u(
        "Neophyte Hybrids",
        {"M": '6"', "WS": "4+", "BS": "4+", "A": "2", "W": "2", "Ld": "6", "Sv": "8+", "N": "10", "Pt": "5"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Neophyte Hybrids"],
        [
            {"name": "Heavy Stubber", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "8+", "armorPen": "10+"},
            {"name": "Mining Laser", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "10+", "armorPen": "6+"},
            {"name": "Seismic Cannon", "type": "Heavy", "range": '24"', "attacks": "1", "skill": "7+", "armorPen": "7+"},
            {"name": "Scavenged Weapons", "type": "Small Arms", "range": '24"', "attacks": "User", "skill": "9+", "armorPen": "10+", "abilities": "Rapid Fire"},
            {"name": "Close Combat Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "8+", "armorPen": "10+"},
        ],
        profiles=[{"M": '6"', "WS": "4+", "BS": "4+", "A": "4", "W": "4", "Ld": "6", "Sv": "8+", "N": "20", "Pt": "10"}],
        options=[
            "Neophyte Hybrids are a unit that contains 10 models. It can contain 20 models (Power Rating 10). It is equipped with: Scavenged Weapons; Close Combat Weapons.",
            "This unit can also be equipped with up to two of the following in any combination (Power Rating +1 per weapon): 1 Heavy Stubber; 1 Mining Laser; 1 Seismic Cannon.",
        ],
    ),
    "Brood Brothers Infantry Squad": u(
        "Brood Brothers Infantry Squad",
        {"M": '6"', "WS": "4+", "BS": "4+", "A": "2", "W": "2", "Ld": "6", "Sv": "10+", "N": "10", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "Brood Brothers", "Light", "Infantry", "Brood Brothers Infantry Squad"],
        [
            {"name": "Autocannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "8+", "armorPen": "8+"},
            {"name": "Heavy Bolter", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "7+", "armorPen": "9+"},
            {"name": "Lascannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "10+", "armorPen": "5+"},
            {"name": "Missile Launcher", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "7+", "armorPen": "7+"},
            {"name": "Mortar", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "8+", "armorPen": "10+", "abilities": "Barrage"},
            {"name": "Lasguns", "type": "Small Arms", "range": '24"', "attacks": "User", "skill": "8+", "armorPen": "10+", "abilities": "Rapid Fire"},
            {"name": "Close Combat Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "8+", "armorPen": "10+"},
        ],
        profiles=[{"M": '6"', "WS": "4+", "BS": "4+", "A": "4", "W": "4", "Ld": "6", "Sv": "10+", "N": "20", "Pt": "6"}],
        options=[
            "A Brood Brothers Infantry Squad is a unit that contains 10 models. It can contain 20 models (Power Rating 6). It can contain 1 weapons team model instead of 2 other models (Power Rating +1). It is equipped with: Lasguns; Close Combat Weapons.",
            "If this unit contains a weapons team model, it must also be equipped with one of the following: 1 Autocannon; 1 Heavy Bolter; 1 Lascannon; 1 Missile Launcher; 1 Mortar.",
        ],
    ),
    "Acolyte Iconward": u(
        "Acolyte Iconward",
        {"M": '6"', "WS": "3+", "BS": "3+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "1", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Acolyte Iconward"],
        [{"name": "Rending Claw", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "8+", "armorPen": "9+"}],
        'Sacred Cult Banner: Morale tests taken for friendly <Cult> units are automatically passed whilst they are within 6" of this unit.\n'
        'Nexus of Devotion: Friendly <Cult> Light units have the Ignore Damage (6+) ability whilst they are within 6" of this unit.',
        options=["An Acolyte Iconward is a unit that contains 1 model. It is equipped with: Rending Claw."],
    ),
    "Purestrain Genestealers": u(
        "Purestrain Genestealers",
        {"M": '9"', "WS": "3+", "BS": "-", "A": "1", "W": "1", "Ld": "7", "Sv": "9+", "N": "5", "Pt": "5"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Genestealer", "Purestrain Genestealers"],
        [{"name": "Purestrain Claws", "type": "Melee", "range": "Melee", "attacks": "x3", "skill": "6+", "armorPen": "8+"}],
        profiles=[
            {"M": '9"', "WS": "3+", "BS": "-", "A": "2", "W": "2", "Ld": "7", "Sv": "9+", "N": "10", "Pt": "10"},
            {"M": '9"', "WS": "3+", "BS": "-", "A": "3", "W": "3", "Ld": "7", "Sv": "9+", "N": "15", "Pt": "15"},
            {"M": '9"', "WS": "3+", "BS": "-", "A": "4", "W": "4", "Ld": "7", "Sv": "9+", "N": "20", "Pt": "20"},
        ],
        options=["Purestrain Genestealers are a unit that contains 5 models. It can contain 10 models (Power Rating 10), 15 models (Power Rating 15) or 20 models (Power Rating 20). It is equipped with: Purestrain Claws."],
    ),
    "Aberrants": u(
        "Aberrants",
        {"M": '6"', "WS": "3+", "BS": "6+", "A": "1", "W": "2", "Ld": "6", "Sv": "10+", "N": "5", "Pt": "5"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Aberrants"],
        [{"name": "Aberrant Weapons", "type": "Melee", "range": "Melee", "attacks": "x2", "skill": "5+", "armorPen": "7+"}],
        "Ignore Damage (6+)",
        profiles=[{"M": '6"', "WS": "3+", "BS": "6+", "A": "2", "W": "4", "Ld": "6", "Sv": "10+", "N": "10", "Pt": "9"}],
        options=["Aberrants are a unit that contains 5 models. It can contain 10 models (Power Rating 9). It is equipped with: Aberrant Weapons."],
    ),
    "Hybrid Metamorphs": u(
        "Hybrid Metamorphs",
        {"M": '6"', "WS": "3+", "BS": "4+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "5", "Pt": "4"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Hybrid Metamorphs"],
        [
            {"name": "Metamorph Weapons (Ranged)", "type": "Small Arms", "range": '12"', "attacks": "User", "skill": "7+", "armorPen": "9+"},
            {"name": "Metamorph Weapons (Melee)", "type": "Melee", "range": "Melee", "attacks": "x3", "skill": "7+", "armorPen": "8+"},
        ],
        profiles=[{"M": '6"', "WS": "3+", "BS": "4+", "A": "2", "W": "2", "Ld": "6", "Sv": "10+", "N": "10", "Pt": "8"}],
        options=["Hybrid Metamorphs are a unit that contains 5 models. It can contain 10 models (Power Rating 8). It is equipped with: Metamorph Weapons (Ranged); Metamorph Weapons (Melee)."],
    ),
    "Clamavus": u(
        "Clamavus",
        {"M": '6"', "WS": "3+", "BS": "3+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "1", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Clamavus"],
        [{"name": "Close Combat Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "10+", "armorPen": "10+"}],
        'Scrambler Array: Enemy units that arrive as reinforcements using the Deep Strike ability cannot be set up within 12" of this unit.',
        options=["A Clamavus is a unit that contains 1 model. It is equipped with: Close Combat Weapons."],
    ),
    "Locus": u(
        "Locus",
        {"M": '6"', "WS": "2+", "BS": "3+", "A": "1", "W": "1", "Ld": "6", "Sv": "9+", "N": "1", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Locus"],
        [{"name": "Locus Blades", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "7+", "armorPen": "8+"}],
        'Unquestioning Bodyguard: At the start of the Damage phase, you can select one friendly <Cult> Light Character unit within 6" of this unit; remove up to D3 blast markers from that Character unit and place them next to this unit.',
        options=["A Locus is a unit that contains 1 model. It is equipped with: Locus Blades."],
    ),
    "Sanctus": u(
        "Sanctus",
        {"M": '6"', "WS": "2+", "BS": "2+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "1", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Sanctus"],
        [
            {"name": "Silencer Sniper Rifle", "type": "Small Arms", "range": '36"', "attacks": "User", "skill": "8+", "armorPen": "10+", "abilities": "Sniper"},
            {"name": "Sanctus Bio-dagger", "type": "Melee", "range": "Melee", "attacks": "x2", "skill": "7+", "armorPen": "9+"},
            {"name": "Familiar Claws", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "11+", "armorPen": "12+"},
        ],
        "Infiltrators\nCult Assassin: This unit cannot be a Warlord.",
        options=[
            "A Sanctus is a unit that contains 1 model. It is equipped with: Silencer Sniper Rifle; Familiar Claws.",
            "Instead of 1 Silencer Sniper Rifle, this unit can be equipped with 1 Sanctus Bio-dagger.",
        ],
    ),
    "Kelermorph": u(
        "Kelermorph",
        {"M": '6"', "WS": "3+", "BS": "2+", "A": "1", "W": "1", "Ld": "6", "Sv": "9+", "N": "1", "Pt": "4"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Kelermorph"],
        [
            {"name": "Liberator Autostubs", "type": "Small Arms", "range": '12"', "attacks": "x2", "skill": "8+", "armorPen": "10+"},
            {"name": "Cultist Knife", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "11+", "armorPen": "12+"},
        ],
        'Folk Hero: If this unit successfully wounds an enemy unit with its Liberator Autostubs then, until the end of the turn, re-roll hit rolls of 1 for attacks made with ranged weapons by friendly <Cult> Infantry units whilst they are within 6" of this unit.',
        options=["A Kelermorph is a unit that contains 1 model. It is equipped with: Liberator Autostubs; Cultist Knife."],
    ),
    "Nexos": u(
        "Nexos",
        {"M": '6"', "WS": "3+", "BS": "3+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "1", "Pt": "2"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Nexos"],
        [{"name": "Close Combat Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "10+", "armorPen": "10+"}],
        "Strategic Coordinator: If any friendly units with this ability are on the battlefield at the start of the Generate Command Assets step, you generate one extra Command Asset.",
        options=["A Nexos is a unit that contains 1 model. It is equipped with: Close Combat Weapons."],
    ),
    "Biophagus": u(
        "Biophagus",
        {"M": '6"', "WS": "3+", "BS": "3+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "1", "Pt": "2"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Infantry", "Character", "Biophagus"],
        [{"name": "Injector Goad", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "5+", "armorPen": "12+"}],
        'Genomic Enhancement: At the start of the Action phase, you can enhance one friendly <Cult> Aberrant unit within 1" of this unit. Add 1 to that unit\'s Attacks characteristic until the end of the battle. A unit can only be enhanced once per battle.',
        options=["A Biophagus is a unit that contains 1 model. It is equipped with: Injector Goad."],
    ),
    "Jackal Alphus": u(
        "Jackal Alphus",
        {"M": '14"', "WS": "3+", "BS": "2+", "A": "1", "W": "1", "Ld": "6", "Sv": "10+", "N": "1", "Pt": "5"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Biker", "Character", "Jackal Alphus"],
        [
            {"name": "Jackal Sniper Rifle", "type": "Small Arms", "range": '36"', "attacks": "User", "skill": "8+", "armorPen": "8+", "abilities": "Sniper"},
            {"name": "Close Combat Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "10+", "armorPen": "10+"},
        ],
        "Stealth\n"
        'Priority Target Sighted: When this unit\'s Detachment is chosen to carry out an order, before any actions are made, select one enemy unit visible to and within 36" of this unit. Until the end of the turn, add 1 to hit rolls for attacks made with ranged weapons by friendly <Cult> units whilst they are within 6" of this unit if those attacks target the selected unit. An enemy unit can only be affected by this ability once per turn.',
        options=["A Jackal Alphus is a unit that contains 1 model. It is equipped with: Jackal Sniper Rifle; Close Combat Weapons."],
    ),
    "Atalan Jackals": u(
        "Atalan Jackals",
        {"M": '14"', "WS": "4+", "BS": "4+", "A": "1", "W": "2", "Ld": "6", "Sv": "10+", "N": "5", "Pt": "4"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Light", "Biker", "Atalan Jackals"],
        [
            {"name": "Atalan Incinerator", "type": "Heavy", "range": '12"', "attacks": "1", "skill": "6+", "armorPen": "9+", "abilities": "Inferno"},
            {"name": "Heavy Stubber", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "8+", "armorPen": "10+"},
            {"name": "Mining Laser", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "10+", "armorPen": "6+"},
            {"name": "Autopistols", "type": "Small Arms", "range": '12"', "attacks": "User", "skill": "8+", "armorPen": "10+"},
            {"name": "Close Combat Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "8+", "armorPen": "10+"},
        ],
        profiles=[
            {"M": '14"', "WS": "4+", "BS": "4+", "A": "2", "W": "4", "Ld": "6", "Sv": "10+", "N": "10", "Pt": "8"},
            {"M": '14"', "WS": "4+", "BS": "4+", "A": "3", "W": "6", "Ld": "6", "Sv": "10+", "N": "15", "Pt": "12"},
        ],
        options=[
            "Atalan Jackals are a unit that contains 4 models. It can contain 8 models (Power Rating 8) or 12 models (Power Rating 12). For every 4 models this unit contains, it can contain 1 Atalan Wolfquad model (Power Rating +1 per model). It is equipped with: Autopistols; Close Combat Weapons.",
            "For each Atalan Wolfquad model this unit contains, it must also be equipped with one of the following: 1 Atalan Incinerator; 1 Heavy Stubber; 1 Mining Laser.",
        ],
    ),
    "Achilles Ridgerunners": u(
        "Achilles Ridgerunners",
        {"M": '14"', "WS": "6+", "BS": "4+", "A": "1", "W": "2", "Ld": "5", "Sv": "8+", "N": "1", "Pt": "6"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Heavy", "Vehicle", "Achilles Ridgerunners"],
        [
            {"name": "Heavy Mining Laser", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "9+", "armorPen": "5+"},
            {"name": "Heavy Mortar", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "7+", "armorPen": "9+", "abilities": "Barrage"},
            {"name": "Heavy Stubbers", "type": "Heavy", "range": '36"', "attacks": "x2", "skill": "8+", "armorPen": "10+"},
            {"name": "Missile Launcher", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "7+", "armorPen": "7+"},
            {"name": "Close Combat Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "10+", "armorPen": "10+"},
        ],
        "Infiltrators",
        profiles=[
            {"M": '14"', "WS": "6+", "BS": "4+", "A": "2", "W": "4", "Ld": "5", "Sv": "8+", "N": "2", "Pt": "12"},
            {"M": '14"', "WS": "6+", "BS": "4+", "A": "3", "W": "6", "Ld": "5", "Sv": "8+", "N": "3", "Pt": "18"},
        ],
        options=[
            "Achilles Ridgerunners are a unit that contains 1 model. It can contain 2 models (Power Rating 12) or 3 models (Power Rating 18). It is equipped with: Heavy Stubbers; Close Combat Weapons.",
            "For each model this unit contains, it must also be equipped with one of the following: 1 Heavy Mining Laser; 1 Heavy Mortar; 1 Missile Launcher.",
        ],
    ),
    "Cult Armoured Sentinels": u(
        "Cult Armoured Sentinels",
        {"M": '8"', "WS": "4+", "BS": "4+", "A": "1", "W": "1", "Ld": "5", "Sv": "6+", "N": "1", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "Brood Brothers", "Heavy", "Vehicle", "Cult Armoured Sentinels"],
        [
            {"name": "Autocannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "8+", "armorPen": "8+"},
            {"name": "Heavy Flamer", "type": "Heavy", "range": '8"', "attacks": "1", "skill": "6+", "armorPen": "9+", "abilities": "Inferno"},
            {"name": "Lascannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "10+", "armorPen": "5+"},
            {"name": "Missile Launcher", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "7+", "armorPen": "7+"},
            {"name": "Multi-laser", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "6+", "armorPen": "10+"},
            {"name": "Plasma Cannon", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "7+", "armorPen": "7+", "abilities": "Supercharge"},
            {"name": "Armoured Feet", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "11+", "armorPen": "12+"},
        ],
        profiles=[
            {"M": '8"', "WS": "4+", "BS": "4+", "A": "2", "W": "2", "Ld": "5", "Sv": "6+", "N": "2", "Pt": "6"},
            {"M": '8"', "WS": "4+", "BS": "4+", "A": "3", "W": "3", "Ld": "5", "Sv": "6+", "N": "3", "Pt": "9"},
        ],
        options=[
            "Cult Armoured Sentinels is a unit that contains 1 model. It can contain 2 models (Power Rating 6) or 3 models (Power Rating 9). It is equipped with: Armoured Feet.",
            "For each model this unit contains, it must also be equipped with one of the following: 1 Autocannon; 1 Heavy Flamer; 1 Lascannon; 1 Missile Launcher; 1 Multi-laser; 1 Plasma Cannon.",
        ],
    ),
    "Cult Scout Sentinels": u(
        "Cult Scout Sentinels",
        {"M": '9"', "WS": "4+", "BS": "4+", "A": "1", "W": "1", "Ld": "5", "Sv": "8+", "N": "1", "Pt": "4"},
        ["Tyranids", "Genestealer Cults", "Brood Brothers", "Heavy", "Vehicle", "Cult Scout Sentinels"],
        [
            {"name": "Autocannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "8+", "armorPen": "8+"},
            {"name": "Heavy Flamer", "type": "Heavy", "range": '8"', "attacks": "1", "skill": "6+", "armorPen": "9+", "abilities": "Inferno"},
            {"name": "Lascannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "10+", "armorPen": "5+"},
            {"name": "Missile Launcher", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "7+", "armorPen": "7+"},
            {"name": "Multi-laser", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "6+", "armorPen": "10+"},
            {"name": "Armoured Feet", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "11+", "armorPen": "12+"},
        ],
        "Infiltrators",
        profiles=[
            {"M": '9"', "WS": "4+", "BS": "4+", "A": "2", "W": "2", "Ld": "5", "Sv": "8+", "N": "2", "Pt": "7"},
            {"M": '9"', "WS": "4+", "BS": "4+", "A": "3", "W": "3", "Ld": "5", "Sv": "8+", "N": "3", "Pt": "10"},
        ],
        options=[
            "Cult Scout Sentinels is a unit that contains 1 model. It can contain 2 models (Power Rating 7) or 3 models (Power Rating 10). It is equipped with: Armoured Feet.",
            "For each model this unit contains, it must also be equipped with one of the following: 1 Autocannon; 1 Heavy Flamer; 1 Lascannon; 1 Missile Launcher; 1 Multi-laser.",
        ],
    ),
    "Brood Brothers Heavy Weapons Squad": u(
        "Brood Brothers Heavy Weapons Squad",
        {"M": '6"', "WS": "4+", "BS": "4+", "A": "1", "W": "1", "Ld": "5", "Sv": "10+", "N": "3", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "Brood Brothers", "Light", "Infantry", "Brood Brothers Heavy Weapons Squad"],
        [
            {"name": "Autocannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "8+", "armorPen": "8+"},
            {"name": "Heavy Bolter", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "7+", "armorPen": "9+"},
            {"name": "Lascannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "10+", "armorPen": "5+"},
            {"name": "Missile Launcher", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "7+", "armorPen": "7+"},
            {"name": "Mortar", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "8+", "armorPen": "10+", "abilities": "Barrage"},
            {"name": "Close Combat Weapons", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "8+", "armorPen": "10+"},
        ],
        "Weapon Teams: For the purposes of determining what models a unit can transport, models in this unit are weapons team models.",
        options=[
            "A Brood Brothers Heavy Weapons Squad is a unit that contains 3 models. It is equipped with: Close Combat Weapons.",
            "For each model this unit contains, it must also be equipped with one of the following: 1 Autocannon; 1 Heavy Bolter; 1 Lascannon; 1 Missile Launcher; 1 Mortar.",
        ],
    ),
    "Goliath Rockgrinder": u(
        "Goliath Rockgrinder",
        {"M": '10"', "WS": "4+", "BS": "4+", "A": "1", "W": "2", "Ld": "5", "Sv": "8+", "N": "1", "Pt": "7"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Heavy", "Vehicle", "Transport", "Goliath Rockgrinder"],
        [
            {"name": "Clearance Incinerator", "type": "Heavy", "range": '12"', "attacks": "2", "skill": "6+", "armorPen": "9+", "abilities": "Inferno"},
            {"name": "Heavy Mining Laser", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "9+", "armorPen": "5+"},
            {"name": "Heavy Seismic Cannon", "type": "Heavy", "range": '24"', "attacks": "2", "skill": "7+", "armorPen": "7+"},
            {"name": "Heavy Stubber", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "8+", "armorPen": "10+"},
            {"name": "Drilldozer Blade", "type": "Melee", "range": "Melee", "attacks": "x2", "skill": "7+", "armorPen": "7+"},
        ],
        "Ignore Damage (6+)\n"
        "TRANSPORT: This unit can transport up to 6 friendly <Cult> Infantry models. Each Patriarch model takes the space of 5 other Infantry models.",
        options=[
            "A Goliath Rockgrinder is a unit that contains 1 model. It is equipped with: Heavy Mining Laser; Heavy Stubber; Drilldozer Blade.",
            "Instead of 1 Heavy Mining Laser, this unit can be equipped with one of the following: 1 Clearance Incinerator; 1 Heavy Seismic Cannon.",
        ],
    ),
    "Cult Leman Russ": u(
        "Cult Leman Russ",
        {"M": '10"', "WS": "6+", "BS": "4+", "A": "1", "W": "2", "Ld": "5", "Sv": "6+", "N": "1", "Pt": "8"},
        ["Tyranids", "Genestealer Cults", "Brood Brothers", "Heavy", "Vehicle", "Cult Leman Russ"],
        [
            {"name": "Battle Cannon", "type": "Heavy", "range": '72"', "attacks": "1", "skill": "6+", "armorPen": "6+"},
            {"name": "Eradicator Nova Cannon", "type": "Heavy", "range": '36"', "attacks": "2", "skill": "5+", "armorPen": "9+"},
            {"name": "Exterminator Autocannon", "type": "Heavy", "range": '48"', "attacks": "2", "skill": "6+", "armorPen": "8+"},
            {"name": "Heavy Bolter", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "7+", "armorPen": "9+"},
            {"name": "Heavy Flamer", "type": "Heavy", "range": '8"', "attacks": "1", "skill": "6+", "armorPen": "9+", "abilities": "Inferno"},
            {"name": "Heavy Stubber", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "8+", "armorPen": "10+"},
            {"name": "Lascannon", "type": "Heavy", "range": '48"', "attacks": "1", "skill": "10+", "armorPen": "5+"},
            {"name": "Multi-melta", "type": "Heavy", "range": '24"', "attacks": "1", "skill": "10+", "armorPen": "4+"},
            {"name": "Plasma Cannon", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "7+", "armorPen": "7+", "abilities": "Supercharge"},
            {"name": "Vanquisher Battle Cannon", "type": "Heavy", "range": '72"', "attacks": "1", "skill": "10+", "armorPen": "4+"},
            {"name": "Storm Bolter", "type": "Small Arms", "range": '24"', "attacks": "1", "skill": "9+", "armorPen": "10+", "abilities": "Rapid Fire"},
            {"name": "Grinding Tracks", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "10+", "armorPen": "10+"},
        ],
        "Grinding Advance: When this unit makes a Shoot action, if it has remained stationary or moved a distance less than half its Move characteristic this turn, double the Attacks characteristic of its Battle Cannon, Eradicator Nova Cannon, Exterminator Autocannon and Vanquisher Battle Cannon for that action.",
        options=[
            "A Cult Leman Russ is a unit that contains 1 model. It is equipped with: Battle Cannon; Heavy Bolter; Grinding Tracks.",
            "Instead of 1 Battle Cannon, this unit can be equipped with one of the following: 1 Eradicator Nova Cannon; 1 Exterminator Autocannon; 1 Vanquisher Battle Cannon.",
            "Instead of 1 Heavy Bolter, this unit can be equipped with one of the following: 1 Heavy Flamer; 1 Lascannon.",
            "This unit can also be equipped with one of the following (Power Rating +2): 2 Heavy Bolters; 2 Heavy Flamers; 2 Multi-meltas; 2 Plasma Cannons.",
            "This unit can also be equipped with one of the following (Power Rating +1): 1 Heavy Stubber; 1 Storm Bolter.",
        ],
    ),
    "Goliath Truck": u(
        "Goliath Truck",
        {"M": '12"', "WS": "6+", "BS": "4+", "A": "1", "W": "2", "Ld": "5", "Sv": "8+", "N": "1", "Pt": "6"},
        ["Tyranids", "Genestealer Cults", "<Cult>", "Heavy", "Vehicle", "Transport", "Goliath Truck"],
        [
            {"name": "Heavy Stubber", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "8+", "armorPen": "10+"},
            {"name": "Twin Autocannon", "type": "Heavy", "range": '48"', "attacks": "2", "skill": "8+", "armorPen": "8+"},
            {"name": "Tough Chassis", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "10+", "armorPen": "10+"},
        ],
        "Open-topped, Ignore Damage (6+)\n"
        "TRANSPORT: This unit can transport up to 10 friendly <Cult> Infantry models. Each Patriarch model takes the space of 5 other Infantry models.",
        options=["A Goliath Truck is a unit that contains 1 model. It is equipped with: Heavy Stubber; Twin Autocannon; Tough Chassis."],
    ),
    "Cult Chimera": u(
        "Cult Chimera",
        {"M": '12"', "WS": "6+", "BS": "4+", "A": "1", "W": "2", "Ld": "5", "Sv": "6+", "N": "1", "Pt": "7"},
        ["Tyranids", "Genestealer Cults", "Brood Brothers", "Heavy", "Vehicle", "Transport", "Cult Chimera"],
        [
            {"name": "Heavy Bolter", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "7+", "armorPen": "9+"},
            {"name": "Heavy Flamer", "type": "Heavy", "range": '8"', "attacks": "1", "skill": "6+", "armorPen": "9+", "abilities": "Inferno"},
            {"name": "Heavy Stubber", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "8+", "armorPen": "10+"},
            {"name": "Multi-laser", "type": "Heavy", "range": '36"', "attacks": "1", "skill": "6+", "armorPen": "10+"},
            {"name": "Lasgun Array", "type": "Small Arms", "range": '24"', "attacks": "1", "skill": "8+", "armorPen": "10+", "abilities": "Rapid Fire"},
            {"name": "Storm Bolter", "type": "Small Arms", "range": '24"', "attacks": "1", "skill": "9+", "armorPen": "10+", "abilities": "Rapid Fire"},
            {"name": "Armoured Tracks", "type": "Melee", "range": "Melee", "attacks": "User", "skill": "10+", "armorPen": "10+"},
        ],
        "TRANSPORT: This unit can transport up to 12 friendly Brood Brothers Infantry models. Each weapons team model takes the space of 2 other Infantry models.",
        options=[
            "A Cult Chimera is a unit that contains 1 model. It is equipped with: Heavy Bolter; 2 Lasgun Arrays; Multi-laser; Armoured Tracks.",
            "Instead of 1 Heavy Bolter, this unit can be equipped with 1 Heavy Flamer.",
            "Instead of 1 Multi-laser, this unit can be equipped with one of the following: 1 Heavy Bolter; 1 Heavy Flamer.",
            "This unit can also be equipped with one of the following (Power Rating +1): 1 Heavy Stubber; 1 Storm Bolter.",
        ],
    ),
    "Tectonic Fragdrill": u(
        "Tectonic Fragdrill",
        {"M": "-", "WS": "-", "BS": "-", "A": "-", "W": "-", "Ld": "-", "Sv": "-", "N": "1", "Pt": "3"},
        ["Tyranids", "Genestealer Cults", "Sector Mechanicus", "Tectonic Fragdrill"],
        [],
        "A Tectonic Fragdrill is a unit that contains 1 model. It cannot be set up on an objective marker and must be set up more than 1\" from any other terrain features. After this unit is set up, it is treated as Defensible Terrain, and is no longer considered to be a unit for any rules purposes.\n"
        "SEISMIC QUAKE: Once per battle, at the start of the second or subsequent Action phase, the player who set up this terrain feature can trigger a seismic quake if there are any Genestealer Cults units from their army within 1\" of this terrain feature. If they do, draw a straight imaginary line, 1mm in thickness, from any point of one battlefield edge to any point of another battlefield edge in such a way that it crosses this terrain feature. Roll one D6 for each unit without the Fly keyword and each unit garrisoning a Defensible Terrain feature that this line crosses; on a 5+ place one blast marker next to the unit being rolled for.",
        options=["A Tectonic Fragdrill is a unit that contains 1 model."],
    ),
}

GENESTEALER_CULTS_SLOTS = [
    slot(1, "HQ", GENESTEALER_CULTS["Patriarch"]),
    slot(2, "HQ", GENESTEALER_CULTS["Magus"]),
    slot(3, "HQ", GENESTEALER_CULTS["Primus"]),
    slot(4, "Lord", GENESTEALER_CULTS["Abominant"]),
    slot(5, "Troops", GENESTEALER_CULTS["Acolyte Hybrids"]),
    slot(6, "Troops", GENESTEALER_CULTS["Neophyte Hybrids"]),
    slot(7, "Troops", GENESTEALER_CULTS["Brood Brothers Infantry Squad"]),
    slot(8, "Elites", GENESTEALER_CULTS["Acolyte Iconward"]),
    slot(9, "Elites", GENESTEALER_CULTS["Purestrain Genestealers"]),
    slot(10, "Elites", GENESTEALER_CULTS["Aberrants"]),
    slot(11, "Elites", GENESTEALER_CULTS["Hybrid Metamorphs"]),
    slot(12, "Elites", GENESTEALER_CULTS["Clamavus"]),
    slot(13, "Elites", GENESTEALER_CULTS["Locus"]),
    slot(14, "Elites", GENESTEALER_CULTS["Sanctus"]),
    slot(15, "Elites", GENESTEALER_CULTS["Kelermorph"]),
    slot(16, "Elites", GENESTEALER_CULTS["Nexos"]),
    slot(17, "Elites", GENESTEALER_CULTS["Biophagus"]),
    slot(18, "Fast", GENESTEALER_CULTS["Jackal Alphus"]),
    slot(19, "Fast", GENESTEALER_CULTS["Atalan Jackals"]),
    slot(20, "Fast", GENESTEALER_CULTS["Achilles Ridgerunners"]),
    slot(21, "Heavy", GENESTEALER_CULTS["Cult Armoured Sentinels"]),
    slot(22, "Heavy", GENESTEALER_CULTS["Cult Scout Sentinels"]),
    slot(23, "Heavy", GENESTEALER_CULTS["Brood Brothers Heavy Weapons Squad"]),
    slot(24, "Heavy", GENESTEALER_CULTS["Goliath Rockgrinder"]),
    slot(25, "Heavy", GENESTEALER_CULTS["Cult Leman Russ"]),
    slot(26, "Heavy", GENESTEALER_CULTS["Goliath Truck"]),
    slot(27, "Transport", GENESTEALER_CULTS["Cult Chimera"]),
    slot(28, "Transport", GENESTEALER_CULTS["Goliath Truck"]),
    slot(29, "Air", GENESTEALER_CULTS["Achilles Ridgerunners"]),
    slot(30, "Air", GENESTEALER_CULTS["Cult Scout Sentinels"]),
    slot(31, "Transport", GENESTEALER_CULTS["Goliath Rockgrinder"]),
    slot(32, "Lord", GENESTEALER_CULTS["Tectonic Fragdrill"]),
]
